spring.application.name=JRM

spring.mongodb.uri=mongodb://localhost:1234/jrm

logging.level.org.springframework.security=DEBUG

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# File upload settings
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.tomcat.max-part-count=-1


# Upload directory (create this folder in your project root)
app.upload.dir=uploads